# Generated by Django 3.2 on 2024-03-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image_content',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
