# Generated by Django 3.2 on 2024-03-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_school_name', models.CharField(max_length=75)),
                ('certificate_date', models.CharField(max_length=20, null=True)),
                ('certificate_title', models.CharField(max_length=50)),
                ('certificate_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('contact_title', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=300)),
                ('contact_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('education_school_name', models.CharField(max_length=75)),
                ('education_date', models.CharField(max_length=20, null=True)),
                ('education_title', models.CharField(max_length=50)),
                ('education_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicMail',
            fields=[
                ('mail_id', models.AutoField(primary_key=True, serialize=False)),
                ('mail_first_name', models.CharField(max_length=50)),
                ('mail_last_name', models.CharField(max_length=50)),
                ('mail_address', models.CharField(max_length=100)),
                ('mail_message', models.TextField(max_length=500)),
                ('mail_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.ImageField(upload_to='gallery/')),
                ('image_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_title', models.CharField(max_length=80)),
                ('price_type', models.CharField(choices=[('ucuz', 'En Ucuz'), ('popiler', 'En Popüler'), ('normal', 'Normal')], default='normal', max_length=7)),
                ('price_price', models.IntegerField()),
                ('price_sub_content_1', models.TextField(blank=True, max_length=80, null=True)),
                ('price_sub_content_2', models.TextField(blank=True, max_length=80, null=True)),
                ('price_sub_content_3', models.TextField(blank=True, max_length=80, null=True)),
                ('price_sub_content_4', models.TextField(blank=True, max_length=80, null=True)),
                ('price_sub_content_5', models.TextField(blank=True, max_length=80, null=True)),
                ('price_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=100)),
                ('project_budget', models.CharField(max_length=100, null=True)),
                ('project_delivery_date', models.CharField(max_length=20, null=True)),
                ('project_frontend_tecnologies', models.CharField(max_length=200, null=True)),
                ('project_backend_tecnologies', models.CharField(max_length=200, null=True)),
                ('project_live_url', models.CharField(max_length=150, null=True)),
                ('project_github_url', models.CharField(max_length=150, null=True)),
                ('project_details', models.TextField(max_length=400, null=True)),
                ('project_image_path', models.ImageField(null=True, upload_to='projects/')),
                ('project_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('table_title', models.CharField(max_length=60)),
                ('table_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_left_text', models.TextField(max_length=40)),
                ('content_right_text', models.TextField(null=True)),
                ('table_content_created_at', models.DateTimeField(auto_now_add=True)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.table')),
            ],
        ),
    ]
