# Generated by Django 3.2 on 2024-06-01 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Sertifika ID')),
                ('certificate_school_name', models.CharField(max_length=75, verbose_name='Okul Adı')),
                ('certificate_date', models.CharField(max_length=20, null=True, verbose_name='Tarih')),
                ('certificate_title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('certificate_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Sertifika',
                'verbose_name_plural': 'Sertifikalar',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Eğitim ID')),
                ('education_school_name', models.CharField(max_length=75, verbose_name='Okul Adı')),
                ('education_date', models.CharField(max_length=20, null=True, verbose_name='Tarih')),
                ('education_title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('education_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitim Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='ElectronicMail',
            fields=[
                ('mail_id', models.AutoField(primary_key=True, serialize=False, verbose_name='E-posta ID')),
                ('mail_first_name', models.CharField(max_length=50, verbose_name='Adı')),
                ('mail_last_name', models.CharField(max_length=50, verbose_name='Soyadı')),
                ('mail_address', models.CharField(max_length=100, verbose_name='Adres')),
                ('mail_message', models.TextField(max_length=500, verbose_name='Mesaj')),
                ('mail_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'E-posta',
                'verbose_name_plural': 'E-postalar',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Resim ID')),
                ('image_path', models.ImageField(upload_to='gallery/', verbose_name='Resim Yolu')),
                ('image_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Galeri Resmi',
                'verbose_name_plural': 'Galeri Resimleri',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Fiyat ID')),
                ('price_title', models.CharField(max_length=80, verbose_name='Başlık')),
                ('price_type', models.CharField(choices=[('ucuz', 'En Ucuz'), ('popiler', 'En Popüler'), ('normal', 'Normal')], default='normal', max_length=7, verbose_name='Tür')),
                ('price_price', models.IntegerField(verbose_name='Fiyat')),
                ('price_sub_content_1', models.TextField(blank=True, max_length=80, null=True, verbose_name='Alt İçerik 1')),
                ('price_sub_content_2', models.TextField(blank=True, max_length=80, null=True, verbose_name='Alt İçerik 2')),
                ('price_sub_content_3', models.TextField(blank=True, max_length=80, null=True, verbose_name='Alt İçerik 3')),
                ('price_sub_content_4', models.TextField(blank=True, max_length=80, null=True, verbose_name='Alt İçerik 4')),
                ('price_sub_content_5', models.TextField(blank=True, max_length=80, null=True, verbose_name='Alt İçerik 5')),
                ('price_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Fiyat',
                'verbose_name_plural': 'Fiyatlar',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Proje ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='Proje Adı')),
                ('project_type', models.CharField(max_length=100, verbose_name='Proje Türü')),
                ('project_budget', models.CharField(max_length=100, null=True, verbose_name='Bütçe')),
                ('project_delivery_date', models.CharField(max_length=20, null=True, verbose_name='Teslim Tarihi')),
                ('project_frontend_tecnologies', models.CharField(max_length=200, null=True, verbose_name='Frontend Teknolojileri')),
                ('project_backend_tecnologies', models.CharField(max_length=200, null=True, verbose_name='Backend Teknolojileri')),
                ('project_live_url', models.CharField(max_length=150, null=True, verbose_name='Canlı URL')),
                ('project_github_url', models.CharField(max_length=150, null=True, verbose_name='GitHub URL')),
                ('project_details', models.TextField(max_length=400, null=True, verbose_name='Detaylar')),
                ('project_image_path', models.ImageField(upload_to='projects/', verbose_name='Resim Yolu')),
                ('project_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Tablo ID')),
                ('table_title', models.CharField(max_length=60, verbose_name='Başlık')),
                ('table_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Tablo',
                'verbose_name_plural': 'Tablolar',
            },
        ),
        migrations.CreateModel(
            name='TechStackCategory',
            fields=[
                ('tech_stack_category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Teknoloji Yığını Kategorisi ID')),
                ('tech_stack_category_title', models.CharField(max_length=30, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name': 'Teknoloji Yığını Kategorisi',
                'verbose_name_plural': 'Teknoloji Yığını Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('tech_stack_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Teknoloji Yığını ID')),
                ('tech_stack_title', models.CharField(max_length=30, verbose_name='Başlığı')),
                ('tech_stack_info', models.CharField(max_length=30, null=True, verbose_name='Alt Bilgi')),
                ('tech_stack_image_path', models.ImageField(upload_to='techstacks/', verbose_name='Resim Yolu')),
                ('tech_stack_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.techstackcategory', verbose_name='Kategorisi')),
            ],
            options={
                'verbose_name': 'Teknoloji Yığını',
                'verbose_name_plural': 'Teknoloji Yığınları',
            },
        ),
        migrations.CreateModel(
            name='TableContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False, verbose_name='İçerik ID')),
                ('content_left_text', models.TextField(max_length=40, verbose_name='Sol Metin')),
                ('content_right_text', models.TextField(null=True, verbose_name='Sağ Metin')),
                ('table_content_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.table', verbose_name='Tablo')),
            ],
            options={
                'verbose_name': 'Tablo İçeriği',
                'verbose_name_plural': 'Tablo İçerikleri',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Resim Yolu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Website.project', verbose_name='Projeyi Seç')),
            ],
            options={
                'verbose_name': 'Proje Resmi',
                'verbose_name_plural': 'Proje Resimleri',
            },
        ),
    ]
