# Generated by Django 3.2 on 2024-06-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvInformation',
            fields=[
                ('cv_info_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Cv Bilgisi Id')),
                ('cv_info_title', models.CharField(max_length=30, verbose_name='Cv Adi')),
                ('cv_info_lang', models.CharField(max_length=30, verbose_name='Cv Dili')),
                ('cv_info_path', models.CharField(max_length=30, verbose_name='Cv Linki')),
            ],
            options={
                'verbose_name': 'Cv Bilgisi',
                'verbose_name_plural': 'Cv Bilgileri',
            },
        ),
    ]
