# Generated by Django 3.2 on 2024-03-09 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Sertifika', 'verbose_name_plural': 'Sertifikalar'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Eğitim', 'verbose_name_plural': 'Eğitim Bilgileri'},
        ),
        migrations.AlterModelOptions(
            name='electronicmail',
            options={'verbose_name': 'E-posta', 'verbose_name_plural': 'E-postalar'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Galeri Resmi', 'verbose_name_plural': 'Galeri Resimleri'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Fiyat', 'verbose_name_plural': 'Fiyatlar'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Tablo', 'verbose_name_plural': 'Tablolar'},
        ),
        migrations.AlterModelOptions(
            name='tablecontent',
            options={'verbose_name': 'Tablo İçeriği', 'verbose_name_plural': 'Tablo İçerikleri'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_date',
            field=models.CharField(max_length=20, null=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Sertifika ID'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_school_name',
            field=models.CharField(max_length=75, verbose_name='Okul Adı'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_title',
            field=models.CharField(max_length=50, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='education',
            name='education_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='education',
            name='education_date',
            field=models.CharField(max_length=20, null=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='education',
            name='education_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Eğitim ID'),
        ),
        migrations.AlterField(
            model_name='education',
            name='education_school_name',
            field=models.CharField(max_length=75, verbose_name='Okul Adı'),
        ),
        migrations.AlterField(
            model_name='education',
            name='education_title',
            field=models.CharField(max_length=50, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='electronicmail',
            name='mail_address',
            field=models.CharField(max_length=100, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='electronicmail',
            name='mail_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='electronicmail',
            name='mail_first_name',
            field=models.CharField(max_length=50, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='electronicmail',
            name='mail_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='E-posta ID'),
        ),
        migrations.AlterField(
            model_name='electronicmail',
            name='mail_last_name',
            field=models.CharField(max_length=50, verbose_name='Soyadı'),
        ),
        migrations.AlterField(
            model_name='electronicmail',
            name='mail_message',
            field=models.TextField(max_length=500, verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Resim ID'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_path',
            field=models.ImageField(upload_to='gallery/', verbose_name='Resim Yolu'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Fiyat ID'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_price',
            field=models.IntegerField(verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_sub_content_1',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='Alt İçerik 1'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_sub_content_2',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='Alt İçerik 2'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_sub_content_3',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='Alt İçerik 3'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_sub_content_4',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='Alt İçerik 4'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_sub_content_5',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='Alt İçerik 5'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_title',
            field=models.CharField(max_length=80, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_type',
            field=models.CharField(choices=[('ucuz', 'En Ucuz'), ('popiler', 'En Popüler'), ('normal', 'Normal')], default='normal', max_length=7, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_backend_tecnologies',
            field=models.CharField(max_length=200, null=True, verbose_name='Backend Teknolojileri'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_budget',
            field=models.CharField(max_length=100, null=True, verbose_name='Bütçe'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_delivery_date',
            field=models.CharField(max_length=20, null=True, verbose_name='Teslim Tarihi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_details',
            field=models.TextField(max_length=400, null=True, verbose_name='Detaylar'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_frontend_tecnologies',
            field=models.CharField(max_length=200, null=True, verbose_name='Frontend Teknolojileri'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_github_url',
            field=models.CharField(max_length=150, null=True, verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Proje ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image_path',
            field=models.ImageField(null=True, upload_to='projects/', verbose_name='Resim Yolu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_live_url',
            field=models.CharField(max_length=150, null=True, verbose_name='Canlı URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100, verbose_name='Proje Adı'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(max_length=100, verbose_name='Proje Türü'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Tablo ID'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_title',
            field=models.CharField(max_length=60, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='tablecontent',
            name='content_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='İçerik ID'),
        ),
        migrations.AlterField(
            model_name='tablecontent',
            name='content_left_text',
            field=models.TextField(max_length=40, verbose_name='Sol Metin'),
        ),
        migrations.AlterField(
            model_name='tablecontent',
            name='content_right_text',
            field=models.TextField(null=True, verbose_name='Sağ Metin'),
        ),
        migrations.AlterField(
            model_name='tablecontent',
            name='table_content_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='tablecontent',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.table', verbose_name='Tablo'),
        ),
    ]
