# Generated by Django 3.2 on 2024-06-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_alter_cvinformation_cv_info_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinformation',
            name='cv_info_lang',
            field=models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English'), ('ru', 'Русский')], default='normal', max_length=30, verbose_name='Cv Dili'),
        ),
    ]
