# Generated by Django 3.2 on 2024-03-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_auto_20240330_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image_path',
            field=models.ImageField(upload_to='projects/', verbose_name='Resim Yolu'),
        ),
    ]
