# Generated by Django 3.2 on 2024-04-03 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_alter_project_project_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStackCategory',
            fields=[
                ('tech_stack_category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Teknoloji Yığını Kategorisi ID')),
                ('tech_stack_category_title', models.CharField(max_length=30, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name': 'Teknoloji Yığını Kategorisi',
                'verbose_name_plural': 'Teknoloji Yığını Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('tech_stack_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Teknoloji Yığını ID')),
                ('tech_stack_title', models.CharField(max_length=30, verbose_name='Başlığı')),
                ('tech_stack_info', models.CharField(max_length=30, null=True, verbose_name='Alt Bilgi')),
                ('tech_stack_image_path', models.ImageField(upload_to='techstacks/', verbose_name='Resim Yolu')),
                ('tech_stack_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stacks', to='Website.techstackcategory')),
            ],
            options={
                'verbose_name': 'Teknoloji Yığını',
                'verbose_name_plural': 'Teknoloji Yığınları',
            },
        ),
    ]
