# Generated by Django 3.2 on 2024-04-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_techstack_techstackcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techstack',
            old_name='tech_stack_category',
            new_name='tech_stack_category_id',
        ),
    ]
