services:

  db-portfolio:
      image: postgres:15
      environment:
        - POSTGRES_DB=portfolio-project-db
        - POSTGRES_USER=east-khan
        - POSTGRES_PASSWORD=Matematik.555
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - portfolio-network
      healthcheck:  # Yeni eklenen healthcheck
        test: ["CMD-SHELL", "pg_isready -U east-khan -d portfolio-project-db"]
        interval: 5s
        timeout: 5s
        retries: 5

  backend-portfolio:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=db-portfolio
    ports:
      - "8001:8001"
    depends_on:
      db-portfolio:
        condition: service_healthy  
    command: >
      sh -c "python manage.py makemigrations Website api&& python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:8001"
    networks:
      - portfolio-network
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media


  frontend-portfolio:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend_portfolio
    ports:
      - "83:80"  
    volumes:
      - ./frontend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - backend-portfolio
    networks:
      - portfolio-network


networks:
  portfolio-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
