services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3002:3002"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://backend:8001
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true    
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:8.0  
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3306"  
    environment:
      MYSQL_DATABASE: portfolio-project-db 
      MYSQL_ROOT_PASSWORD: 1234  
      MYSQL_ROOT_HOST: '%'  
    volumes:
      - mysql_data:/var/lib/mysql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-uroot", "-p1234"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: